name: "Client"
on:
  push:
    branches:
      - main
      - test-ci
    tags:
    - '*'
jobs:
  lint:
    defaults:
      run:
        working-directory: ./client
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Download dependencies
      run: yarn
    - name: Run lint
      run: yarn lint
  test:
    defaults:
      run:
        working-directory: ./client
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Download dependencies
      run: yarn
    - name: Run tests
      run: yarn test