name: "Client"
on:
  push:
    branches:
      - main
      - test-ci
    tags:
      - "*"
env:
  SERVICE: client
jobs:
  lint:
    defaults:
      run:
        working-directory: ./${{ env.client }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Download dependencies
        run: yarn
      - name: Run lint
        run: yarn lint
  test:
    defaults:
      run:
        working-directory: ./client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: echo $PWD
      - name: Download dependencies
        run: yarn
      - name: Run tests
        run: yarn test
  docker:
    permissions:
      packages: write
      contents: read
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    defaults:
      run:
        working-directory: ./client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./client/
          push: true
          tags: client:latest
