name: "Server"
env:
  SERVICE: server
on:
  push:
    branches:
      - main
      - test-ci
    tags:
      - "*"
    paths:
      - "server/**"
      - ".github/workflows/server.yaml"
permissions:
  packages: write
  contents: read
jobs:
  lint:
    defaults:
      run:
        working-directory: ./${{ env.SERVICE }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Download dependencies
        run: yarn
      - name: Run lint
        run: yarn lint
  test:
    defaults:
      run:
        working-directory: ./${{ env.SERVICE }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: echo $PWD
      - name: Download dependencies
        run: yarn
      - name: Run tests
        run: yarn test
  docker:
    env:
      REGISTRY: ghcr.io
    defaults:
      run:
        working-directory: ./${{ env.SERVICE }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert repository name to lowercase
        id: repo-name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ env.SERVICE }}/
          push: true
          tags: ghcr.io/${{ steps.repo-name.outputs.lowercase }}/${{ env.SERVICE }}:latest
